FROM python:3.13.2

WORKDIR /app

COPY requirements_full.txt /app/
# COPY requirements.txt /app/
# COPY add_requirements.txt /app/

RUN pip install -r requirements_full.txt --no-deps
# RUN pip install -r requirements.txt --no-deps
# RUN pip install -r add_requirements.txt

# RUN pip install blinker

COPY . /app/

CMD ["flask", "run"]